export const TOOLS = [
  // ─── FREE TOOLS ──────────────────────────────────────────────────────────────
  {
    id: 'merge-pdf',
    name: 'Merge PDF',
    description: 'Combine multiple PDFs into one seamless document',
    icon: '⊕',
    color: '#3b82f6',
    gradient: 'linear-gradient(135deg, #1e3a5f, #0d1f3c)',
    category: 'organize',
    premium: false,
    endpoint: '/api/convert/merge-pdf',
    multiFile: true,
    accepts: ['.pdf'],
    popular: true,
  },
  {
    id: 'split-pdf',
    name: 'Split PDF',
    description: 'Extract pages or split into multiple documents',
    icon: '⊘',
    color: '#6366f1',
    gradient: 'linear-gradient(135deg, #2d1b69, #1e1148)',
    category: 'organize',
    premium: false,
    endpoint: '/api/convert/split-pdf',
    multiFile: false,
    accepts: ['.pdf'],
    popular: true,
  },
  {
    id: 'compress-pdf',
    name: 'Compress PDF',
    description: 'Reduce file size while preserving quality',
    icon: '⊖',
    color: '#10b981',
    gradient: 'linear-gradient(135deg, #064e3b, #022c22)',
    category: 'optimize',
    premium: false,
    endpoint: '/api/convert/compress-pdf',
    multiFile: false,
    accepts: ['.pdf'],
    popular: true,
  },
  {
    id: 'rotate-pdf',
    name: 'Rotate PDF',
    description: 'Rotate pages to the correct orientation',
    icon: '↻',
    color: '#f59e0b',
    gradient: 'linear-gradient(135deg, #451a03, #2d1a00)',
    category: 'organize',
    premium: false,
    endpoint: '/api/convert/rotate-pdf',
    multiFile: false,
    accepts: ['.pdf'],
    popular: false,
  },
  {
    id: 'pdf-to-jpg',
    name: 'PDF to JPG',
    description: 'Convert PDF pages to high-quality images',
    icon: '🖼',
    color: '#ec4899',
    gradient: 'linear-gradient(135deg, #500724, #2d0416)',
    category: 'convert',
    premium: false,
    endpoint: '/api/convert/pdf-to-jpg',
    multiFile: false,
    accepts: ['.pdf'],
    popular: true,
  },
  {
    id: 'jpg-to-pdf',
    name: 'JPG to PDF',
    description: 'Convert images to PDF format instantly',
    icon: '📄',
    color: '#14b8a6',
    gradient: 'linear-gradient(135deg, #042f2e, #021a1a)',
    category: 'convert',
    premium: false,
    endpoint: '/api/convert/jpg-to-pdf',
    multiFile: true,
    accepts: ['.jpg', '.jpeg', '.png', '.gif', '.webp', '.tiff'],
    popular: false,
  },
  // ─── PREMIUM TOOLS ────────────────────────────────────────────────────────────
  {
    id: 'pdf-to-word',
    name: 'PDF to Word',
    description: 'Convert PDF to editable Word documents',
    icon: 'W',
    color: '#2563eb',
    gradient: 'linear-gradient(135deg, #1e3a8a, #0f1f4d)',
    category: 'convert',
    premium: true,
    endpoint: '/api/convert/pdf-to-word',
    multiFile: false,
    accepts: ['.pdf'],
    popular: true,
  },
  {
    id: 'word-to-pdf',
    name: 'Word to PDF',
    description: 'Convert Word documents to PDF format',
    icon: 'W→',
    color: '#3b82f6',
    gradient: 'linear-gradient(135deg, #1e3a5f, #0d1f3c)',
    category: 'convert',
    premium: true,
    endpoint: '/api/convert/word-to-pdf',
    multiFile: false,
    accepts: ['.doc', '.docx'],
    popular: false,
    comingSoon: true,
  },
  {
    id: 'pdf-to-excel',
    name: 'PDF to Excel',
    description: 'Extract tables from PDF to Excel spreadsheets',
    icon: 'X',
    color: '#10b981',
    gradient: 'linear-gradient(135deg, #064e3b, #022c22)',
    category: 'convert',
    premium: true,
    endpoint: '/api/convert/pdf-to-excel',
    multiFile: false,
    accepts: ['.pdf'],
    popular: false,
    comingSoon: true,
  },
  {
    id: 'pdf-to-ppt',
    name: 'PDF to PPT',
    description: 'Convert PDF slides to PowerPoint presentations',
    icon: 'P',
    color: '#f97316',
    gradient: 'linear-gradient(135deg, #431407, #1c0a03)',
    category: 'convert',
    premium: true,
    endpoint: '/api/convert/pdf-to-ppt',
    multiFile: false,
    accepts: ['.pdf'],
    popular: false,
    comingSoon: true,
  },
  {
    id: 'protect-pdf',
    name: 'Protect PDF',
    description: 'Add password protection to your PDFs',
    icon: '🔐',
    color: '#ef4444',
    gradient: 'linear-gradient(135deg, #450a0a, #1f0505)',
    category: 'security',
    premium: true,
    endpoint: '/api/convert/protect-pdf',
    multiFile: false,
    accepts: ['.pdf'],
    popular: false,
  },
  {
    id: 'watermark-pdf',
    name: 'Watermark PDF',
    description: 'Add custom text or image watermarks to PDFs',
    icon: '◈',
    color: '#8b5cf6',
    gradient: 'linear-gradient(135deg, #2e1065, #160933)',
    category: 'security',
    premium: true,
    endpoint: '/api/convert/watermark-pdf',
    multiFile: false,
    accepts: ['.pdf'],
    popular: false,
  },
  {
    id: 'unlock-pdf',
    name: 'Unlock PDF',
    description: 'Remove password protection from PDFs',
    icon: '🔓',
    color: '#f59e0b',
    gradient: 'linear-gradient(135deg, #451a03, #2d1a00)',
    category: 'security',
    premium: true,
    endpoint: '/api/convert/unlock-pdf',
    multiFile: false,
    accepts: ['.pdf'],
    popular: false,
    comingSoon: true,
  },
  {
    id: 'ocr-pdf',
    name: 'OCR PDF',
    description: 'Make scanned PDFs searchable with text recognition',
    icon: '⚡',
    color: '#06b6d4',
    gradient: 'linear-gradient(135deg, #0c4a6e, #082f49)',
    category: 'optimize',
    premium: true,
    endpoint: '/api/convert/ocr-pdf',
    multiFile: false,
    accepts: ['.pdf'],
    popular: false,
    comingSoon: true,
  },
  {
    id: 'pdf-to-html',
    name: 'PDF to HTML',
    description: 'Convert PDF documents to web-ready HTML',
    icon: '</> ',
    color: '#e11d48',
    gradient: 'linear-gradient(135deg, #4c0519, #1f0209)',
    category: 'convert',
    premium: true,
    endpoint: '/api/convert/pdf-to-html',
    multiFile: false,
    accepts: ['.pdf'],
    popular: false,
    comingSoon: true,
  },
  {
    id: 'pdf-to-pdfa',
    name: 'PDF to PDF/A',
    description: 'Convert PDFs to archival-compliant PDF/A format',
    icon: 'A',
    color: '#64748b',
    gradient: 'linear-gradient(135deg, #1e293b, #0f172a)',
    category: 'optimize',
    premium: true,
    endpoint: '/api/convert/pdf-to-pdfa',
    multiFile: false,
    accepts: ['.pdf'],
    popular: false,
    comingSoon: true,
  },
  {
    id: 'repair-pdf',
    name: 'Repair PDF',
    description: 'Fix corrupted or damaged PDF files',
    icon: '🔧',
    color: '#84cc16',
    gradient: 'linear-gradient(135deg, #1a2e05, #0d1a03)',
    category: 'optimize',
    premium: true,
    endpoint: '/api/convert/repair-pdf',
    multiFile: false,
    accepts: ['.pdf'],
    popular: false,
    comingSoon: true,
  },
];

export const CATEGORIES = [
  { id: 'all', label: 'All Tools', count: TOOLS.length },
  { id: 'convert', label: 'Convert', count: TOOLS.filter(t => t.category === 'convert').length },
  { id: 'organize', label: 'Organize', count: TOOLS.filter(t => t.category === 'organize').length },
  { id: 'optimize', label: 'Optimize', count: TOOLS.filter(t => t.category === 'optimize').length },
  { id: 'security', label: 'Security', count: TOOLS.filter(t => t.category === 'security').length },
];

export const getToolById = (id) => TOOLS.find(t => t.id === id);
export const getFreeTools = () => TOOLS.filter(t => !t.premium);
export const getPremiumTools = () => TOOLS.filter(t => t.premium);
export const getPopularTools = () => TOOLS.filter(t => t.popular);
